### Use Balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1234500
}

### Use Balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1234500
}

### Cancel Balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "77410bc9e1fd4e07b2a1a12cf46019d2",
  "accountNumber": "1000000000",
  "amount": 1234500
}

### Query Transaction
GET http://localhost:8080/transaction/31adc3f8c74a45d8b761e8443d6860de
Content-Type: application/json